./combine_NCD_Ballermix_Set100.sh
./combine_NCD_Ballermix_Set10.sh
./combine_NCD_Ballermix_Set11.sh
./combine_NCD_Ballermix_Set12.sh
./combine_NCD_Ballermix_Set13.sh
./combine_NCD_Ballermix_Set14.sh
./combine_NCD_Ballermix_Set15.sh
./combine_NCD_Ballermix_Set16.sh
./combine_NCD_Ballermix_Set17.sh
./combine_NCD_Ballermix_Set18.sh
./combine_NCD_Ballermix_Set19.sh
./combine_NCD_Ballermix_Set1.sh
./combine_NCD_Ballermix_Set20.sh
./combine_NCD_Ballermix_Set21.sh
./combine_NCD_Ballermix_Set22.sh
./combine_NCD_Ballermix_Set23.sh
./combine_NCD_Ballermix_Set24.sh
./combine_NCD_Ballermix_Set25.sh
./combine_NCD_Ballermix_Set26.sh
./combine_NCD_Ballermix_Set27.sh
./combine_NCD_Ballermix_Set28.sh
./combine_NCD_Ballermix_Set29.sh
./combine_NCD_Ballermix_Set2.sh
./combine_NCD_Ballermix_Set30.sh
./combine_NCD_Ballermix_Set31.sh
./combine_NCD_Ballermix_Set32.sh
./combine_NCD_Ballermix_Set33.sh
./combine_NCD_Ballermix_Set34.sh
./combine_NCD_Ballermix_Set35.sh
./combine_NCD_Ballermix_Set36.sh
./combine_NCD_Ballermix_Set37.sh
./combine_NCD_Ballermix_Set38.sh
./combine_NCD_Ballermix_Set39.sh
./combine_NCD_Ballermix_Set3.sh
./combine_NCD_Ballermix_Set40.sh
./combine_NCD_Ballermix_Set41.sh
./combine_NCD_Ballermix_Set42.sh
./combine_NCD_Ballermix_Set43.sh
./combine_NCD_Ballermix_Set44.sh
./combine_NCD_Ballermix_Set45.sh
./combine_NCD_Ballermix_Set46.sh
./combine_NCD_Ballermix_Set47.sh
./combine_NCD_Ballermix_Set48.sh
./combine_NCD_Ballermix_Set49.sh
./combine_NCD_Ballermix_Set4.sh
./combine_NCD_Ballermix_Set50.sh
./combine_NCD_Ballermix_Set51.sh
./combine_NCD_Ballermix_Set52.sh
./combine_NCD_Ballermix_Set53.sh
./combine_NCD_Ballermix_Set54.sh
./combine_NCD_Ballermix_Set55.sh
./combine_NCD_Ballermix_Set56.sh
./combine_NCD_Ballermix_Set57.sh
./combine_NCD_Ballermix_Set58.sh
./combine_NCD_Ballermix_Set59.sh
./combine_NCD_Ballermix_Set5.sh
./combine_NCD_Ballermix_Set60.sh
./combine_NCD_Ballermix_Set61.sh
./combine_NCD_Ballermix_Set62.sh
./combine_NCD_Ballermix_Set63.sh
./combine_NCD_Ballermix_Set64.sh
./combine_NCD_Ballermix_Set65.sh
./combine_NCD_Ballermix_Set66.sh
./combine_NCD_Ballermix_Set67.sh
./combine_NCD_Ballermix_Set68.sh
./combine_NCD_Ballermix_Set69.sh
./combine_NCD_Ballermix_Set6.sh
./combine_NCD_Ballermix_Set70.sh
./combine_NCD_Ballermix_Set71.sh
./combine_NCD_Ballermix_Set72.sh
./combine_NCD_Ballermix_Set73.sh
./combine_NCD_Ballermix_Set74.sh
./combine_NCD_Ballermix_Set75.sh
./combine_NCD_Ballermix_Set76.sh
./combine_NCD_Ballermix_Set77.sh
./combine_NCD_Ballermix_Set78.sh
./combine_NCD_Ballermix_Set79.sh
./combine_NCD_Ballermix_Set7.sh
./combine_NCD_Ballermix_Set80.sh
./combine_NCD_Ballermix_Set81.sh
./combine_NCD_Ballermix_Set82.sh
./combine_NCD_Ballermix_Set83.sh
./combine_NCD_Ballermix_Set84.sh
./combine_NCD_Ballermix_Set85.sh
./combine_NCD_Ballermix_Set86.sh
./combine_NCD_Ballermix_Set87.sh
./combine_NCD_Ballermix_Set88.sh
./combine_NCD_Ballermix_Set89.sh
./combine_NCD_Ballermix_Set8.sh
./combine_NCD_Ballermix_Set90.sh
./combine_NCD_Ballermix_Set91.sh
./combine_NCD_Ballermix_Set92.sh
./combine_NCD_Ballermix_Set93.sh
./combine_NCD_Ballermix_Set94.sh
./combine_NCD_Ballermix_Set95.sh
./combine_NCD_Ballermix_Set96.sh
./combine_NCD_Ballermix_Set97.sh
./combine_NCD_Ballermix_Set98.sh
./combine_NCD_Ballermix_Set99.sh
./combine_NCD_Ballermix_Set9.sh
