---
output:
  pdf_document: default
  html_document: default
---
```{r echo=FALSE,  message=FALSE, warning=FALSE}
# Load ggplot2 library
library(ggpointdensity)
library(tidyverse)
library(gridExtra)
library(ggsignif)
library(ggpointdensity)
library(ggpubr)
library(ggrepel)

```

# CLR

### Genes tagged to track their locacion on the different plots.

```{r echo=FALSE,  message=FALSE, warning=FALSE}
clr_100_sets <- read.table("results/final_clr_table_by_sets.txt",
                           header = TRUE)

bias_and_all <- read.table('input/2023_08_22_MASTER_cleaned_all_pops.txt',
                           header = TRUE)

clr_100_sets <- merge(bias_and_all, clr_100_sets, by = "gene")

clr_100_sets <- clr_100_sets %>%
  rowwise() %>%
  mutate(
    "shuffled_pops_mean100" = mean(c_across(starts_with("mean_clr_set"))),
    "shuffled_pops_SD100" = mean(c_across(starts_with("sd_clr_set")))
  )

real_4_pops_clr <- read.table("results/real_4_pops_clr.txt", 
                                header = TRUE)
real_4_pops_clr <- real_4_pops_clr[, 1:3]
colnames(real_4_pops_clr)[colnames(real_4_pops_clr) == "Mean_Pops_Clr"] <- "Mean_RealPops_Clr"

clr_100_sets <- merge(clr_100_sets, real_4_pops_clr, by = "gene")
clr_100_sets$candens <- as.factor(clr_100_sets$candens)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Information for ggplot anotation
gene1 <- subset(clr_100_sets, gene == "LOC105207562")
gene2 <- subset(clr_100_sets, gene == "LOC105200045")
gene3 <- subset(clr_100_sets, gene == "LOC105202344")
gene4 <- subset(clr_100_sets, gene == "LOC105199771")

three_genes <- rbind(gene1, gene4)
clr_100_sets$row_name <- rownames(clr_100_sets)

```

```{r echo=FALSE, message=FALSE, warning=FALSE}

gene_in_common_test1 <- intersect(clr_100_sets %>% subset(shuffled_pops_mean100 >= 15),
                                  clr_100_sets %>% subset(clr >= 20))

gene_in_common_test1$gene

```


# Real vs shuffled 4 pops 

```{r echo=FALSE, message=FALSE, warning=FALSE}


ggplot(clr_100_sets %>% arrange(candens), 
       aes(x = Mean_RealPops_Clr, y = shuffled_pops_mean100, shape = candens, 
           colour =shuffled_pops_SD100 )) +
  geom_point(size = 4, alpha = 0.6)+
  # Adding linear regression line
geom_smooth(method = "lm", se = TRUE, color = "grey") +  
   #Add names to selected points
  geom_label_repel(data = gene_in_common_test1 , 
                   aes(label = row_name), colour = "black",
                   size= 2, nudge_x = 2, nudge_y = 3, direction = "both",
                   box.padding = 0.3, max.overlaps = 50) +
  #clr_100_sets %>% subset(shuffled_pops_mean100 >= 15
  # Change colors
  scale_colour_viridis_c(option = "D", direction = 1, name = "SD") + 
  geom_abline(slope = 1, intercept = 0, linetype = "dashed")+
  #Change axis labels
  labs(subtitle = "CLR Shuffled vs original subpopulations",
       y = "Mean shuffled subpopulations", x = "Mean original subpopulations") + 
  guides(shape = FALSE) +
  theme_minimal()

# Create a basic density plot
# ggplot(data = clr_100_sets, aes(x = shuffled_pops_SD100)) +
#   geom_density(fill = "blue", color = "black", alpha = 0.55) +
#   labs(y = "Density")+
#   geom_vline(xintercept = 6.461141)+
#   geom_vline(xintercept = mean(clr_100_sets$shuffled_pops_SD100, na.rm = TRUE),
#              linetype = "dotted") +
#   theme_minimal()


```


```{r echo=FALSE, message=FALSE, warning=FALSE}

# #summary of lm od triagles email Richard
# 
# #model <- lm(clr_100_sets$Mean_RealPops_Clr ~ clr_100_sets$shuffled_pops_mean100)
# 
# candidates_only <- subset(clr_100_sets, 
#                           candens == 1) 
# 
# model_candidates_only <- lm(candidates_only$shuffled_pops_mean100 ~ candidates_only$Mean_RealPops_Clr)
# summary(model_candidates_only)
# 
# 
# mod3 <- lm(shuffled_pops_mean100 ~ Mean_RealPops_Clr, 
#            offset = Mean_RealPops_Clr,
#            data = candidates_only)
# summary(mod3)
# 
# 
# mod4 <- lm(shuffled_pops_mean100 ~ 1,
#            offset = Mean_RealPops_Clr,
#            data = candidates_only)
# 
# summary(mod4)
# 
# anova(mod4, mod3)

```



```{r echo=FALSE, message=FALSE, warning=FALSE}

ggplot(clr_100_sets, 
       aes(x = clr, y = Mean_RealPops_Clr, colour = shuffled_pops_mean100,
           shape = candens)) +
  geom_point(size = 3, alpha = 0.6) +
  # Adding linear regression line
  #geom_smooth(method = "lm", se = TRUE, color = "grey") +  
  # Add names to selected points
  geom_label_repel(data = gene_in_common_test1, #clr_100_sets %>% subset(clr >= 22)
                   aes(label = row_name), colour = "black",
                   size= 2, nudge_x = 3, nudge_y = 6, direction = "both",
                   box.padding = 0.3, max.overlaps = 50) +
  # Change colors
 scale_colour_viridis_c(option = "D", direction = 1, name = "Shuffled pops") + 
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  #Change axis labels
  labs(y = "Mean 4 Real pops", x = "All 240 samples", 
       subtitle = "CLR Real 4 subpops vs values for total samples") + 
  guides(shape = FALSE) +
  theme_minimal()

```


```{r echo=FALSE, message=FALSE, warning=FALSE}

ggplot(clr_100_sets, 
       aes(x = clr, y = shuffled_pops_mean100, colour = shuffled_pops_SD100,
           shape = candens)) +
  geom_point(size = 3, alpha = 0.6) +
  # Adding linear regression line
 #geom_smooth(method = "lm", se = TRUE, color = "grey") +  
  # Add names to selected points
  geom_label_repel(data = gene_in_common_test1, #clr_100_sets %>% subset(clr >= 22)
                   aes(label = row_name), colour = "black",
                   size= 2, nudge_x = 3, nudge_y = 6, direction = "both",
                   box.padding = 0.3, max.overlaps = 50) +
  # Change colors
 scale_colour_viridis_c(option = "D", direction = 1) + 
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  #Change axis labels
  labs(y = "Mean Shuffled 400 subpops", x = "All 240 samples", 
       subtitle = "CLR Shuffled supops vs values for total samples") + 
  guides(shape = FALSE) +
  theme_minimal()



# I want to know how many candens and labeled as "false positive?".  
# Because are intrinsic to the whole samples or because they are products of  
# geographic structure


```
