# Combined based on density

```{r echo=FALSE,  message=FALSE, warning=FALSE}
# Load ggplot2 library
library(ggpointdensity)
library(tidyverse)
library(gridExtra)
library(ggsignif)
library(ggpointdensity)
library(ggpubr)
library(ggrepel)

```

```{r echo=FALSE,  message=FALSE, warning=FALSE}

density_100_sets <- read.table("results/final_density_by_sets.txt",
                           header = TRUE)
                        
bias_and_all <- read.table('input/2023_08_22_MASTER_cleaned_all_pops.txt',
                           header = TRUE)                      

density_100_sets <- merge(bias_and_all, density_100_sets, by = "gene")

density_100_sets <- density_100_sets %>%
  rowwise() %>%
  mutate(
    "shuffled_pops_mean100" = mean(c_across(starts_with("mean_density_set"))),
    "shuffled_pops_SD100" = mean(c_across(starts_with("sd_density_set")))
  )

real_4_pops_density <- read.table("results/real_4_pops_density.txt", 
                                header = TRUE)
real_4_pops_density <- real_4_pops_density[, 1:3]
colnames(real_4_pops_density)[colnames(real_4_pops_density) == "means_pops_density"] <- "Mean_RealPops_density"

density_100_sets <- merge(density_100_sets, real_4_pops_density, by = "gene")
density_100_sets$candens <- as.factor(density_100_sets$candens)


```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Information for ggplot annotation
gene1 <- subset(density_100_sets, gene == "LOC105207562")
gene2 <- subset(density_100_sets, gene == "LOC105200045")
gene3 <- subset(density_100_sets, gene == "LOC105202344")
gene4 <- subset(density_100_sets, gene == "LOC105199771")

three_genes <- rbind(gene1, gene4)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}

gene_in_common_test1 <- intersect(density_100_sets %>% subset(shuffled_pops_mean100 >= 15),
                                  density_100_sets %>% subset(clr >= 20))

genes_names <- subset(density_100_sets, Mean_RealPops_density <0.010) %>%
  subset(shuffled_pops_mean100 < 0.007)

genes_names$gene
```


# Real vs shuffled 4 pops 

```{r echo=FALSE, message=FALSE, warning=FALSE}

ggplot(density_100_sets %>% arrange(shuffled_pops_mean100) %>% arrange(candens),
       aes(x = 1-Mean_RealPops_density, y = 1-shuffled_pops_mean100, shape = candens,
           colour = shuffled_pops_SD100)) +
  geom_point(size = 4, alpha = 0.6)+
  # Adding linear regression line
  #geom_smooth(method = "lm", se = TRUE, color = "grey") +  
  # Add names to selected points
  #  geom_label_repel(data = genes_names, aes(label = gene), colour = "black",
  #                   size= 2, nudge_x = 0.002, nudge_y = 0.003, 
  #                   direction = "both",
  #                   box.padding = 0.3, max.overlaps = 50) +
  # # Change colors
  scale_colour_viridis_c(option = "B", direction = 1, name = "SD for shuffeled") + 
  geom_abline(slope = 1, intercept = 0, linetype = "dashed")+
  #Change axis labels
  labs(y = "Mean of shuffled 400 locations", x = "Mean four original locations", 
  ) + 
  guides(shape = FALSE) +
  theme_minimal(base_size = 15)

```

Immune genes

```{r echo=FALSE, message=FALSE, warning=FALSE}
density_100_sets$immune <- as.factor(density_100_sets$immune)
ggplot(density_100_sets %>% arrange(candens) %>% arrange(immune),
       aes(x = 1-Mean_RealPops_density, y = 1-shuffled_pops_mean100, shape = candens,
           colour = immune)) +
  geom_point(size = 4, alpha = 0.6)+
  scale_colour_viridis_d(option = "F", direction = -1) + 
  geom_abline(slope = 1, intercept = 0, linetype = "dashed")+
  #Change axis labels
  labs(y = "Mean of shuffled 400 locations", x = "Mean four original locations", 
  ) + 
  guides(shape = FALSE) +
  theme_minimal(base_size = 15)

```

```{r echo=FALSE, message=FALSE, warning=FALSE}
density_100_sets$immune <- as.factor(density_100_sets$immune)
ggplot(density_100_sets %>% arrange(candens) %>% arrange(immune)%>% subset(candens ==1),
       aes(x = 1-Mean_RealPops_density, y = 1-shuffled_pops_mean100, shape = candens,
           colour = immune)) +
  geom_point(size = 4, alpha = 0.6)+
  scale_colour_viridis_d(option = "F", direction = -1) + 
  geom_abline(slope = 1, intercept = 0, linetype = "dashed")+
  #Change axis labels
  labs(y = "Mean of shuffled 400 locations", x = "Mean four original locations", 
  ) + 
  guides(shape = FALSE) +
  theme_minimal(base_size = 15)

```


BUSCO genes 
```{r echo=FALSE, message=FALSE, warning=FALSE}
density_100_sets$hymenop <- as.factor(density_100_sets$hymenop)
ggplot(density_100_sets %>% arrange(candens) %>% arrange(hymenop) %>% subset(candens ==1),
       aes(x = 1-Mean_RealPops_density, y = 1-shuffled_pops_mean100, shape = candens,
           colour = hymenop)) +
  geom_point(size = 4, alpha = 0.6)+
  scale_colour_viridis_d(option = "C", direction = -1) + 
  geom_abline(slope = 1, intercept = 0, linetype = "dashed")+
  #Change axis labels
  labs(y = "Mean of shuffled 400 locations", x = "Mean four original locations", 
  ) + 
  guides(shape = FALSE) +
  theme_minimal(base_size = 15)

```

Drosophila genes

```{r echo=FALSE, message=FALSE, warning=FALSE}
density_100_sets$drosophila <- as.factor(density_100_sets$drosophila)
ggplot(density_100_sets %>% arrange(candens) %>% arrange(drosophila),
       aes(x = 1-Mean_RealPops_density, y = 1-shuffled_pops_mean100, shape = candens,
           colour = drosophila)) +
  geom_point(size = 4, alpha = 0.6)+
  scale_colour_viridis_d(option = "B", direction = -1) + 
  geom_abline(slope = 1, intercept = 0, linetype = "dashed")+
  #Change axis labels
  labs(y = "Mean of shuffled 400 locations", x = "Mean four original locations", 
  ) + 
  guides(shape = FALSE) +
  theme_minimal(base_size = 15)

```



```{r echo=FALSE, message=FALSE, warning=FALSE}

ggplot(density_100_sets %>% 
         arrange(shuffled_pops_mean100) %>% subset(candens ==1),
       aes(x = 1-Mean_RealPops_density, y = 1-shuffled_pops_mean100,
           colour = shuffled_pops_SD100)) +
  geom_point(size = 4, alpha = 0.6, shape = 17)+
  # Adding linear regression line
  #geom_smooth(method = "lm", se = TRUE, color = "grey") +  
  # Add names to selected points
   geom_label_repel(data = genes_names, aes(label = gene), colour = "black",
                    size= 2, nudge_x = 0.002, nudge_y = 0.003, 
                    direction = "both",
                    box.padding = 0.3, max.overlaps = 50) +
  # Change colors
  scale_colour_viridis_c(option = "B", direction = 1, 
                         name = "SD for shuffeled") + 
  geom_abline(slope = 1, intercept = 0, 
              linetype = "dashed") +
  #Change axis labels
  labs(y = "Mean of shuffled 400 locations",
       x = "Mean four original locations", ) + 
  guides(shape = FALSE) +
  theme_minimal()

```

```{r echo=FALSE, message=FALSE, warning=FALSE}

ggplot(density_100_sets %>% arrange(candens), 
       aes(x = 1-Mean_RealPops_density, y = 1-shuffled_pops_mean100, colour = candens,
          shape = candens)) +
  geom_point(size = 4, alpha = 0.6)+
  # Adding linear regression line
  geom_smooth(method = "lm", se = TRUE, color = "grey") +  
  # Add names to selected points
  geom_label_repel(data = genes_names, aes(label = gene), colour = "black",
                   size= 2, nudge_x = -0.0005, nudge_y = 0.002, 
                   direction = "both",
                   box.padding = 0.3, max.overlaps = 50) +
  # Change colors
  scale_colour_viridis_d(option = "E", direction = -1) + 
   geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  # geom_abline(slope = 1, intercept = 0.001, linetype="dashed", color="red") +
  # geom_abline(slope = 1, intercept = -0.001, linetype="dashed", color="red") +
  #Change axis labels
  labs(y = "Mean Shuffled 400 pops", x = "Mean 4 Real pops", 
       subtitle = "Density Shuffled vs Real subpopulations") + 
  guides(shape = FALSE) +
  theme_minimal()
```







```{r echo=FALSE, message=FALSE, warning=FALSE}

# Subset the data for candens == 1
subset_data <- subset(density_100_sets, candens == 1)

# Fit a linear regression model using the subset
model <- lm(shuffled_pops_mean100 ~ Mean_RealPops_density, data = subset_data)

# Predict and get confidence intervals for the entire dataset
predictions <- predict(model, newdata = density_100_sets, interval = "confidence", level = 0.95)

# Add the predictions and intervals to the original data
density_100_sets$predicted <- predictions[,1]
density_100_sets$lwr <- predictions[,2]
density_100_sets$upr <- predictions[,3]

# Add a column to mark genes that fall within the confidence interval
density_100_sets$selected <- ifelse(density_100_sets$shuffled_pops_mean100 >= density_100_sets$lwr & 
                                    density_100_sets$shuffled_pops_mean100 <= density_100_sets$upr, 1, 0)

density_100_sets$selected <- as.factor(density_100_sets$selected)

# Remove temporary columns
 density_100_sets <- density_100_sets[, !names(density_100_sets) %in% c("predicted", "lwr", "upr")]


density_100_sets <- density_100_sets %>%
  mutate(category = case_when(
    selected == 1 & candens == 1 ~ "selected_1_candens_1",
    #selected == 1 & candens == 0 ~ "selected_1_candens_0",
    selected == 0 & candens == 0 ~ "selected_0_candens_0",
    selected == 0 & candens == 1 ~ "selected_0_candens_1",
    TRUE ~ NA_character_
  ))

nrow(subset(density_100_sets, category =="selected_1_candens_1"))
```



```{r echo=FALSE, message=FALSE, warning=FALSE}

ggplot(density_100_sets %>% arrange(category), 
       aes(x = Mean_RealPops_density, y = shuffled_pops_mean100, shape = candens,
           colour = category)) +
  geom_point(size = 4, alpha = 0.6)+
  geom_smooth(data = subset(density_100_sets, candens == 1), 
              aes(x = Mean_RealPops_density, y = shuffled_pops_mean100), 
              method = "lm", se = TRUE, color = "grey") + 
  # Add names to selected points
  geom_label_repel(data = genes_names, aes(label = gene), colour = "black",
                   size= 2, nudge_x = -0.0005, nudge_y = 0.002, 
                   direction = "both",
                   box.padding = 0.3, max.overlaps = 50) +
  # Change colors
  scale_colour_viridis_d(option = "B", direction = -1) + 
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  # geom_abline(slope = 1, intercept = 0.001, linetype="dashed", color="red") +
  # geom_abline(slope = 1, intercept = -0.001, linetype="dashed", color="red") +
  #Change axis labels
  labs(y = "Mean Shuffled 400 pops", x = "Mean 4 Real pops", 
       subtitle = "Density Shuffled vs Real subpopulations") + 
  guides(shape = FALSE) +
  theme_minimal()
```

```{r echo=FALSE, message=FALSE, warning=FALSE}

distance_threshold <- 0.001
density_100_sets$in_area <- ifelse(abs(density_100_sets$Mean_RealPops_density
                                       - density_100_sets$shuffled_pops_mean100)
                                   <= distance_threshold, 1, 0)

nrow(subset(density_100_sets, in_area == 1) %>% subset(candens == 1))

density_100_sets$in_area <- as.factor(density_100_sets$in_area)

density_100_sets$area_candi <- ifelse(density_100_sets$in_area == 1 & density_100_sets$candens == 1,
                                      1,0)
nrow(subset(density_100_sets, area_candi == 1))

# density_100_sets$area_candi <- with(density_100_sets,
#              ifelse(in_area == 1 & candens == 1, 2,
#                     ifelse(in_area == 1 & candens == 0, 1,
#                            ifelse(in_area == 0 & candens == 0, 0, NA))))
#

density_100_sets <- density_100_sets %>%
  mutate(category1to1 = case_when(
    area_candi == 1 & candens == 1 ~ "selected_1_candens_1",
    #selected == 1 & candens == 0 ~ "selected_1_candens_0",
    area_candi == 0 & candens == 0 ~ "selected_0_candens_0",
    area_candi == 0 & candens == 1 ~ "selected_0_candens_1",
    TRUE ~ NA_character_
  ))

density_100_sets$area_candi <- as.factor(density_100_sets$area_candi)
density_100_sets$category1to1 <- as.factor(density_100_sets$category1to1)

```


```{r echo=FALSE, message=FALSE, warning=FALSE}

ggplot(density_100_sets %>% arrange(category1to1), 
       aes(x = Mean_RealPops_density, y = shuffled_pops_mean100, shape = candens,
           colour = category1to1)) +
  geom_point(size = 4, alpha = 0.6)+
  geom_smooth(data = subset(density_100_sets, candens == 1), 
              aes(x = Mean_RealPops_density, y = shuffled_pops_mean100), 
              method = "lm", se = TRUE, color = "grey") + 
  # Add names to selected points
  geom_label_repel(data = genes_names, aes(label = gene), colour = "black",
                   size= 2, nudge_x = -0.0005, nudge_y = 0.002, 
                   direction = "both",
                   box.padding = 0.3, max.overlaps = 50) +
  # Change colors
  scale_colour_viridis_d(option = "B", direction = -1) + 
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  # geom_abline(slope = 1, intercept = 0.001, linetype="dashed", color="red") +
  # geom_abline(slope = 1, intercept = -0.001, linetype="dashed", color="red") +
  #Change axis labels
  labs(y = "Mean Shuffled 400 pops", x = "Mean 4 Real pops", 
       subtitle = "Density Shuffled vs Real subpopulations") + 
  guides(shape = FALSE) +
  theme_minimal()
```


```{r echo=FALSE, message=FALSE, warning=FALSE}

ggplot(density_100_sets, 
       aes(x = density, y = shuffled_pops_mean100, colour = shuffled_pops_SD100)) +
  geom_point(size = 3, alpha = 0.6) +
  # Adding linear regression line
  geom_smooth(method = "lm", se = TRUE, color = "grey") +  
  # Add names to selected points
   geom_label_repel(data = genes_names, aes(label = gene), colour = "black",
                   size= 2, nudge_x = -0.0005, nudge_y = 0.002, 
                   direction = "both",
                   box.padding = 0.3, max.overlaps = 50) +
  # Change colors
 scale_colour_viridis_c(option = "B", direction = 1) + 
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  #Change axis labels
  labs(y = "Mean Shuffled 400 subpops", x = "All 240 samples", 
       subtitle = "Density Shuffled supops vs values for total samples") + 
  #guides(shape = FALSE) +
  theme_minimal()

```

```{r echo=FALSE, message=FALSE, warning=FALSE}

ggplot(density_100_sets, 
       aes(x = density, y = Mean_RealPops_density, colour = shuffled_pops_mean100)) +
  geom_point(size = 3, alpha = 0.6) +
  # Adding linear regression line
  geom_smooth(method = "lm", se = TRUE, color = "grey") +  
  # Add names to selected points
  geom_label_repel(data = genes_names, aes(label = gene), colour = "black",
                   size= 2, nudge_x = -0.0005, nudge_y = 0.002, 
                   direction = "both",
                   box.padding = 0.3, max.overlaps = 50) +
  # Change colors
 scale_colour_viridis_c(option = "B", direction = 1) + 
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  #Change axis labels
  labs(y = "Mean 4 Real pops", x = "All 240 samples", 
       subtitle = "Density Real 4 subpops vs values for total samples") + 
  #guides(shape = FALSE) +
  theme_minimal()

```



```{r echo=FALSE, message=FALSE, warning=FALSE}

ggplot(density_100_sets %>% arrange(candens), 
       aes(x = density, y = shuffled_pops_mean100, colour = shuffled_pops_SD100,
           shape = candens)) +
  geom_point(size = 4, alpha = 0.75) +
  # Adding linear regression line
  geom_smooth(method = "lm", se = TRUE, color = "grey") +  
  # Add names to selected points
  geom_label_repel(data = genes_names, aes(label = gene), colour = "black",
                   size= 2, nudge_x = -0.0005, nudge_y = 0.002, 
                   direction = "both",
                   box.padding = 0.3, max.overlaps = 50) +
  # Change colors
  scale_colour_viridis_c(option = "B", direction = -1, 
                         name = "mean of pops SD") + #, 
                        #  labels = c("No","Yes")) + 
  #Change axis labels
  labs(y = "Mean 100 x 4 subpops", x = "Whole population", 
       subtitle = "Combined statistics by density", shape = "Candidate") + 
  #guides(shape = FALSE) +
  geom_hline(yintercept = quantile(density_100_sets$popsmean100, 0.01, 
                                   na.rm = TRUE), 
             linetype = "dashed", size = 0.5) +
  geom_vline(xintercept = quantile(density_100_sets$density, 0.01, 
                                   na.rm = TRUE),
             linetype = "dashed", size = 0.5) +
  theme_minimal()

```

